### ISSUE TITLE
Can't get result that matches the "Depth"

### ISSUE THREAD

**Issue by enzyme69** [coolzilj/Blender-ControlNet#1]
Error message:
`TypeError: Script.process() missing 4 required positional arguments: 'no_image_generation', 'max_generations', 'magic_model', and 'magic_blocklist_regex'`

I am wondering also if "pose" can be used?

**Comment by coolzilj** [comment]
Did you update your A1111 and Mikubill/sd-webui-controlnet to latest version?
Haven't seen this error msg before.

**Comment by enzyme69** [comment]
I updated all the script and getting more error: -- is this because I use dynamic prompting as well? 

And do I need that hash bracket on the model? Where to find this number? Yes I got the smaller diff model for the pose.

```
To create a public link, set `share=True` in `launch()`.
Error running process: /Users/jimmygunawan/stable-diffusion-webui/extensions/sd-dynamic-prompts/scripts/dynamic_prompting.py
Traceback (most recent call last):
  File "/Users/jimmygunawan/stable-diffusion-webui/modules/scripts.py", line 386, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 18 required positional arguments: 'is_enabled', 'is_combinatorial', 'combinatorial_batches', 'is_magic_prompt', 'is_feeling_lucky', 'is_attention_grabber', 'min_attention', 'max_attention', 'magic_prompt_length', 'magic_temp_value', 'use_fixed_seed', 'unlink_seed_from_prompt', 'disable_negative_prompt', 'enable_jinja_templates', 'no_image_generation', 'max_generations', 'magic_model', and 'magic_blocklist_regex'

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/applications.py", line 125, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/jimmygunawan/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 189, in txt2img
    processed = process_images(p)
  File "/Users/jimmygunawan/stable-diffusion-webui/modules/processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "/Users/jimmygunawan/stable-diffusion-webui/modules/processing.py", line 713, in process_images_inner
    extra_networks.deactivate(p, extra_network_data)
UnboundLocalError: local variable 'extra_network_data' referenced before assignment

```

**Comment by enzyme69** [comment]
I disabled "dynamic prompting" and it seems to work. Expecting to use img2img and other options.

But the code is clear and it make use the API to talk to webUI! Very promising.

I want to try the "hed" preprocessing etc and also maybe "openpose" preprocessing.
