### ISSUE TITLE
txt2image but No correlation between Blender and the result

### ISSUE THREAD

**Issue by enzyme69** [coolzilj/Blender-ControlNet#2]
This time no error message.... however I tried many times and just realized I am not really getting any relationship between Blender original render and the processed via webUI ControlNet. My code might be wrong.

It's almost like the check is turned off when I send the command from Blender via F12. I did get the render before after:

![1677273243-1-before](https://user-images.githubusercontent.com/3952687/221296148-b840896b-095d-4658-801d-9d32d42a39d3.png)

![1677273243-2-after](https://user-images.githubusercontent.com/3952687/221296130-6fc4064d-cfba-4840-8dfd-a44f13627688.png)

Only if I use the same image render output and do it manually on webUI, it works.
![00068-1347600930](https://user-images.githubusercontent.com/3952687/221296229-7e672084-c3de-43bd-bcc8-4a6348f65d8e.png)

**Comment by enzyme69** [comment]
Does the hash matter in the model name? [fef5e48e] is mine. I did not type it on the hardcode python script.

**Comment by enzyme69** [comment]
When the txt2img does nothing, I use img2img and getting error:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/applications.py", line 125, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/Users/jimmygunawan/stable-diffusion-webui/venv/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/jimmygunawan/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/api.py", line 321, in img2img
    processed = process_images(p)
  File "/Users/jimmygunawan/stable-diffusion-webui/modules/processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "/Users/jimmygunawan/stable-diffusion-webui/modules/processing.py", line 577, in process_images_inner
    p.init(p.all_prompts, p.all_seeds, p.all_subseeds)
  File "/Users/jimmygunawan/stable-diffusion-webui/modules/processing.py", line 1015, in init
    image = image.to(shared.device)
  File "/Users/jimmygunawan/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/Users/jimmygunawan/stable-diffusion-webui/modules/sd_hijack_utils.py", line 26, in __call__
    return self.__sub_func(self.__orig_func, *args, **kwargs)
  File "/Users/jimmygunawan/stable-diffusion-webui/modules/mac_specific.py", line 39, in <lambda>
    CondFunc('torch.Tensor.to', lambda orig_func, self, *args, **kwargs: orig_func(self.contiguous(), *args, **kwargs),
TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.
```

**Comment by coolzilj** [comment]
I'm facing the same problem after updating Mikubill/sd-webui-controlnet to latest version last night.
Tried rollbacking to previous commit, eg: f94b453d10c2eb4e3ad57b7cdfdd17e60a557b3e fix it.

> Does the hash matter in the model name? [fef5e48e] is mine. I did not type it on the hardcode python script.
Yes, hash matters. 
You can get the whole cn models list here:
http://localhost:7860/docs#/default/model_list_controlnet_model_list_get

**Comment by Mikubill** [comment]
Maybe related: https://github.com/Mikubill/sd-webui-controlnet/pull/194#issuecomment-1445051668

**Comment by coolzilj** [comment]
> Maybe related: [Mikubill/sd-webui-controlnet#194 (comment)](https://github.com/Mikubill/sd-webui-controlnet/pull/194#issuecomment-1445051668)

Thx, didn't know that.
