### ISSUE TITLE
Webui api memory.py error: raise WouldBlock

### ISSUE THREAD

**Issue by YourFriendlyNeighborhoodMONKE** [coolzilj/Blender-ControlNet#22]
Hi,

I'm trying to get the example template with the script as instructed.

I'm getting the following error:

```
API error: POST: http://localhost:7860/sdapi/v1/txt2img {'error': 'TypeError', 'detail': '', 'body': '', 'errors': 'not all arguments converted during string formatting'}
Traceback (most recent call last):
  File "M:\SDSYS\AUTO\venv\lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
  File "M:\SDSYS\AUTO\venv\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock
```

memory.py, above those two lines defines the condition for rising WouldBlock as the following:

`:raises ~anyio.WouldBlock: if there are no items in the buffer and no tasks`

My noob guess makes me think that Blender fails to send the files to the api
It manages to load the first (depth) model correctly before the error

Help to resolve this will be rewarded with an imaginary banana!

**Comment by coolzilj** [comment]
It seems that the latest version of Automatic1111 has broken many extensions. I suspect that this issue may be related to the update of Automatic1111 or the ControlNet extension. If possible, try rolling back to the previous version. 
Good luck monkey.
