### ISSUE TITLE
the script doesnt work 

### ISSUE THREAD

**Issue by kotaxyz** [coolzilj/Blender-ControlNet#23]
hello there ,thanks alot for this awesome script ,i have a problem when i try to run the script and render i get unrelated image due to the controlnet not working 

error running process: I:\stable-diffusion-webui\extensions\sd-webui-cutoff\scripts\cutoff.py
Traceback (most recent call last):
  File "I:\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "I:\stable-diffusion-webui\extensions\sd-webui-cutoff\scripts\cutoff.py", line 210, in process
    if targets_ is None or len(targets_) == 0:
TypeError: object of type 'bool' has no len()

Error running process: I:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
Traceback (most recent call last):
  File "I:\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "I:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 515, in process
    if (KEYROW in p.prompt.upper() or KEYCOL in p.prompt.upper() or DELIMROW in aratios):
TypeError: argument of type 'bool' is not iterable

Error running process: I:\stable-diffusion-webui\extensions\stable-diffusion-webui-aesthetic-gradients\scripts\aesthetic.py
Traceback (most recent call last):
  File "I:\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "I:\stable-diffusion-webui\extensions\stable-diffusion-webui-aesthetic-gradients\scripts\aesthetic.py", line 36, in process
    aesthetic.set_aesthetic_params(p, float(aesthetic_lr), float(aesthetic_weight), int(aesthetic_steps), aesthetic_imgs, aesthetic_slerp, aesthetic_imgs_text, aesthetic_slerp_angle, aesthetic_text_negative)
ValueError: could not convert string to float: ''

**Comment by kotaxyz** [comment]
i solved it , it was a problem with my controlnet extension not updated
