### ISSUE TITLE
error while rendering gives unrelated image to depth map

### ISSUE THREAD

**Issue by kotaxyz** [coolzilj/Blender-ControlNet#3]
hi mates i get this error also it gives unrelated image to the depth map 

`Error running process: I:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
Traceback (most recent call last):
  File "I:\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
  File "I:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 571, in process
    else self.build_control_model(p, unet, model, lowvram)
  File "I:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 423, in build_control_model
    raise RuntimeError(f"model not found: {model}")
RuntimeError: model not found: diff_control_sd15_depth_fp16 [978ef0a1]

Error running process: I:\stable-diffusion-webui\extensions\stable-diffusion-webui-aesthetic-gradients\scripts\aesthetic.py
Traceback (most recent call last):
  File "I:\stable-diffusion-webui\modules\scripts.py", line 386, in process
    script.process(p, *script_args)
TypeError: AestheticScript.process() missing 8 required positional arguments: 'aesthetic_weight', 'aesthetic_steps', 'aesthetic_lr', 'aesthetic_slerp', 'aesthetic_imgs', 'aesthetic_imgs_text', 'aesthetic_slerp_angle', and 'aesthetic_text_negative'

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "I:\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 94, in receive
    return self.receive_nowait()
  File "I:\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 77, in call_next
    message = await recv_stream.receive()
  File "I:\stable-diffusion-webui\venv\lib\site-packages\anyio\streams\memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "I:\stable-diffusion-webui\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 106, in __call__
    response = await self.dispatch_func(request, call_next)
  File "I:\stable-diffusion-webui\modules\api\api.py", line 96, in log_and_time
    res: Response = await call_next(req)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 80, in call_next
    raise app_exc
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\base.py", line 69, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "I:\stable-diffusion-webui\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "I:\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "I:\stable-diffusion-webui\venv\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "I:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\api.py", line 190, in txt2img
    processed = process_images(p)
  File "I:\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "I:\stable-diffusion-webui\modules\processing.py", line 713, in process_images_inner
    extra_networks.deactivate(p, extra_network_data)
UnboundLocalError: local variable 'extra_network_data' referenced before assignment

`

**Comment by enzyme69** [comment]
You need to have that exact model and with the same hash code. You can download here:
https://huggingface.co/kohya-ss/ControlNet-diff-modules/tree/main

![Screenshot 2023-02-26 at 10 07 34 pm](https://user-images.githubusercontent.com/3952687/221406785-fff9a41a-0fb6-4063-8305-6c8e3bedb250.png)

**Comment by coolzilj** [comment]
Make sure you have downloaded the exact ControlNet model first.
And after that make sure you have the right name for controlnet_model, hash does matter. 
You can get your local installed ControlNet models list from [here](http://localhost:7860/docs#/default/model_list_controlnet_model_list_get).

**Comment by kotaxyz** [comment]
thanks mates i was using the default controlnet model i will try it

**Comment by kotaxyz** [comment]
it worked thanks again
